name: Lint Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Switch directory and run build test
        run: |
          cd frontend && npm install && npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Switch directory and run lint test
        run: |
          cd frontend && npm install && npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Switch directory and run format test
        run: |
          cd frontend && npm install && npm run format:test
